using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Enemigo_Ver_Gesti칩n_Efectos_Sonido : MonoBehaviour
{
    string tagObjetivo = "Enemigo";  // El tag del objeto que desencadenar치 el sonido
    public AudioClip sonido;  // El sonido que se reproducir치

    private void OnTriggerEnter(Collider collision)
    {

        AudioSource.PlayClipAtPoint(sonido, transform.position);
        Debug.Log("Alcachofa");
        // Verificar si el objeto que entr칩 tiene el tag deseado
        if (collision.gameObject.tag == tagObjetivo)
        {
            // Reproducir el sonido
            
        }
    }
}
